class EazyDrummer{
    //easy drummer 3
    constructor(){
        this._map = {
            "Clap": 1,
            "Cymbal Crash 1 Bow Tip": 84,
            "Cymbal Crash 1 Bow Tip Alternative": 87,
            "Cymbal Crash 1 Hit": 86,
            "Cymbal Crash 1 Hit Alternative": 55,
            "Cymbal Crash 1 Mute/Choke": 83,
            "Cymbal Crash 1 Mute/Choke Alternative": 56,
            "Cymbal Crash 2 Bow Tip": 27,
            "Cymbal Crash 2 Bow Tip Alternative": 89,
            "Cymbal Crash 2 Hit": 49,
            "Cymbal Crash 2 Hit Alternative": [28,91],
            "Cymbal Crash 2 Mute/Choke": 50,
            "Cymbal Crash 2 Mute/Choke Alternative": 94,
            "Cymbal Crash 3 Bow Tip": 31,
            "Cymbal Crash 3 Bow Tip Alternative": 101,
            "Cymbal Crash 3 Hit": 57,
            "Cymbal Crash 3 Hit Alternative": [32,103],
            "Cymbal Crash 3 Mute/Choke": 58,
            "Cymbal Crash 3 Mute/Choke Alternative": [106,107],
            "Cymbal Crash 4 Bow Tip": 96,
            "Cymbal Crash 4 Hit": 98,
            "Cymbal Crash 4 Mute/Choke": 95,
            "Cymbal Crash 4 Mute/Choke Alternative": 99,
            "Floortom 1 Hit": 43,
            "Floortom 1 Rim": 74,
            "Floortom 1 Rimshot": 75,
            "Floortom 2 Hit": 41,
            "Floortom 2 Rim": 72,
            "Floortom 2 Rimshot": 73,
            "Hi Hat Cc Edge": 7,
            "Hi Hat Cc Edge Alternative": [18,20],
            "Hi Hat Cc Tip": 8,
            "Hi Hat Cc Tip Alternative": [9,19],
            "Hi Hat Closed Edge": 22,
            "Hi Hat Closed Edge Alternative": [65,122],
            "Hi Hat Closed Tip": 61,
            "Hi Hat Closed Tip Alternative": [11,42,119],
            "Hi Hat Loose": 64,
            "Hi Hat Loose Alternative": 120,
            "Hi Hat Loose Tip": 12,
            "Hi Hat Open 1": 24,
            "Hi Hat Open 1 Tip": 13,
            "Hi Hat Open 2": 25,
            "Hi Hat Open 2 Alternative": [46,123],
            "Hi Hat Open 2 Tip": 14,
            "Hi Hat Open 3": 26,
            "Hi Hat Open 3 Tip": 15,
            "Hi Hat Open 4": 60,
            "Hi Hat Open 4 Alternative": 121,
            "Hi Hat Open 4 Tip": 16,
            "Hi Hat Open 5": 124,
            "Hi Hat Open 5 Tip": 17,
            "Hi Hat Pedal Close Foot": 21,
            "Hi Hat Pedal Close Foot Alternative": [10,44],
            "Hi Hat Pedal Splash": 23,
            "Hi Hat Tight Edge": 62,
            "Hi Hat Tight Tip": 63,
            "Kick": 36,
            "Kick Alternative": [34,35],
            "Racktom 1 Hit": 48,
            "Racktom 1 Rim": 81,
            "Racktom 1 Rimshot": 82,
            "Racktom 2 Hit": 47,
            "Racktom 2 Rim": 79,
            "Racktom 2 Rimshot": 80,
            "Racktom 3 Hit": 45,
            "Racktom 3 Rim": 77,
            "Racktom 3 Rimshot": 78,
            "Ride 1 Bell": 53,
            "Ride 1 Bell Alternative": [30,85,88,90,92,93,97,100,102,105,109,112,114,117],
            "Ride 1 Bow Tip": 51,
            "Ride 1 Bow Tip Alternative": [29,104,108,111,113,116],
            "Ride 1 Edge": [59,110,115,52],
            "Ride 1 Mute/Choke": 118,
            "Ride 1 Mute/Choke Alternative": 54,
            "Shaker": 2,
            "Snare Hit": 38,
            "Snare Hit Alternative": [39,66,68,69,70,125,6],
            "Snare Hit Side": 33,
            "Snare Rim": 71,
            "Snare Rim Alternative": 76,
            "Snare Rimshot": 40,
            "Snare Rimshot Alternative": 126,
            "Snare Sidestick": 37,
            "Snare Sidestick Alternative": [67,127],
            "Tambourine": 3
        }
    }

    get map(){
        return this._map;
    }
}
